apiVersion: v1
kind: pod
metadata:
  name: test-pod
  labels:
    app.kubernets.io/name: myApp
spec:
  containers:
  - name: test
    image: busybox:v1
    command: ["sh", "-c", "echo hehe"]

  - name: test1
    image: busybox:v2
    command: ['sh', '-c', '']
  
  initContainers:
  - name: init
    image: busybox:v1
    command: ['sh', '-c', 'sleep;']


